### ISSUE TITLE
needs to be uncommented

### ISSUE THREAD

**Issue by avishwanath28** [mitchellkilborn/PubFinReplication#7]
https://github.com/mitchellkilborn/PubFinReplication/blob/40b2a7715ab953b693e22303c66ee4f32a55a90e/PrepEPFunctions.R#L71

or else this won't run properly. i assume you commented it because you set the argument in source() in the RunAnalyses.R file. So maybe do something like

`if(runIndividually == T){TotalReps = 1000}`

**Comment by mitchellkilborn** [comment]
Fixed this with the exists() function in PrepEPFunctions.R, good catch.
